sudo: required
language: java
install: true
jdk: oraclejdk8

services:
  - docker
  

script:
  - gradle build sonarqube -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
  
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $DOCKER_USER/code .
  - docker push $DOCKER_USER/code
