spring:
  profiles: test
  redis:
    database: 0
    host: 10.64.13.80
    port: 6379
    
#  datasource:
#    druid:
#      driverClassName: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@10.64.26.45:1521:xe
#      username: root
#      password: root
#      filters: stat
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   
#  datasource:
#    druid:
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://10.64.26.44:3306/new_titancode_test?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#      filters: stat
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.64.11.73:3306/new_titancode_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Root123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  projectPath: /home/titan-code2/codedir/
  projectZipPath: /home/titan-code2/codedir/zip/
  projectUiPath: /home/titan-code2/ui-code/
  projectUiTempPath: /home/titan-code2/ui-code-temp/
  mybatisGenlibsPath: /home/titan-code2/mybatis-genlibs/
  entityZipPath: /home/titan-code2/codeir/entity/zip/
  entityPath: /home/titan-code2/codeir/entity/
appId:
  url: http://10.64.11.157:8080/rescenter/rest/codeGenerator/api/v1/app/save
token:
  url: http://10.64.19.104:8085/rescenter-rest/ResCenterApi/getUserByToken
res:
  center:
    server: 10.64.19.104:8085