spring:
  profiles: local
  redis:
    database: 0
    host: 10.64.13.80
    port: 6379
  datasource:
    schema: classpath:schema.sql
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${DB_URL}/${DB_NAME}?useUnicode=true&characterEncoding=utf-8
      username: ${DB_USER}
      password: ${DB_PWD}
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  mybatisGenlibsPath: ./mybatis-genlibs/
  rootPath: ${GEN_ROOT_PATH:./code-gen/}
  projectPath: ${generate.rootPath}codedir/
  projectZipPath: ${generate.rootPath}codedir/zip/
  projectUiPath: ${generate.rootPath}ui-code/
  projectUiTempPath: ${generate.rootPath}ui-code-temp/