spring:
  profiles: test
  redis:
    database: 0
    host: 10.64.13.80
    port: 6379
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://${DB_URL}/new_titancode_test?useUnicode=true&characterEncoding=utf-8
      username: ${DB_USER}
      password: ${DB_PWD}
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  projectPath: /home/titan-code2/codedir/
  projectZipPath: /home/titan-code2/codedir/zip/
  projectUiPath: /home/titan-code2/ui-code/
  projectUiTempPath: /home/titan-code2/ui-code-temp/
  mybatisGenlibsPath: /home/titan-code2/mybatis-genlibs/
  entityZipPath: /home/titan-code2/codeir/entity/zip/
  entityPath: /home/titan-code2/codeir/entity/