spring:
  profiles: test
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.64.11.73:3306/new_titancode_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Root123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  projectPath: ./codedir/
  projectZipPath: ./codedir/zip/
  mybatisGenlibsPath: ./mybatis-genlibs/