spring:
  profiles: local
  redis:
    database: 0
    host: 10.64.13.80
    port: 6379
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.64.11.73:3306/new_titancode_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Root123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  projectPath: D:/codedir/
  projectZipPath: D:/codedir/zip/
  projectUiPath: D:/ui-code/mould/
  projectUiTempPath: D:/ui-code-temp/
  mybatisGenlibsPath: D:/mybatis-genlibs/
  entityZipPath: D:/entity/zip/
  entityPath: D:/entity/
appId:
  url: http://10.64.11.157:8080/rescenter/rest/codeGenerator/api/v1/app/save
token:
  url: http://10.64.19.104:8085/rescenter-rest/ResCenterApi/getUserByToken
res:
  center:
    server: 10.64.19.104:8085