spring:
  profiles: local
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.105/hotpot-code?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  mybatisGenlibsPath: ./mybatis-genlibs/
  rootPath: ${GEN_ROOT_PATH:./code-gen/}
  projectPath: ${generate.rootPath}codedir/
  projectZipPath: ${generate.rootPath}codedir/zip/
  projectUiPath: ${generate.rootPath}ui-code/
  projectUiTempPath: ${generate.rootPath}ui-code-temp/