spring:
  profiles: local
  datasource:
    druid:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/new_titancode_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: X19890314
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
generate:
  projectPath: D:/
  projectZipPath: D:/zip/
  projectUiPath: D:/ui-code/mould/
  mybatisGenlibsPath: D:/mybatis-genlibs/