server:
  port: 8080
#  tomcat:
#    remote-ip-header: x-forwarded-for
#    protocol-header: x-forwarded-proto
#    basedir: '/logs'
#    backgroundProcessorDelay: 1
#    accesslog:
#      enabled: true
#      pattern: '%h %t "%r" %s %b %{Location}o'
spring:
  application:
    name: titan-code2
  profiles:
    active: ${PRO_ENV:local}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false